version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dev-dependencies:
        patterns:
          - "MinVer"
          - "Microsoft.SourceLink.GitHub"
          - "Microsoft.NET.Test.Sdk"
          - "xunit*"
          - "Verify*"
          - "coverlet*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"
