variables:
- group: ApiKeys
- name: configuration
  value: Release

trigger:
  batch: true
  branches:
    include:
    - '*'
    exclude:
    - 'noci[/-]*'
  tags:
    include:
    - 'v*'

jobs:

- job: Windows
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: UseDotNet@2
    displayName: 'Use .NET 8.0 sdk'
    inputs:
      packageType: sdk
      version: 8.0.x
  - pwsh: |
      chcp 65001
      dotnet build --configuration $(configuration)
      dotnet test --no-build --configuration $(configuration) --logger 'trx' --logger 'console;verbosity=normal'
  - task: PublishTestResults@2
    condition: always()
    inputs:
      testResultsFormat: 'VSTest'
      testResultsFiles: '**/TestResults/*.trx'

- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: UseDotNet@2
    displayName: 'Use .NET 8.0 sdk'
    inputs:
      packageType: sdk
      version: 8.0.x
  - bash: |
      set -euxo pipefail
      dotnet tool restore
      dotnet build --configuration $(configuration)
      dotnet test --no-build --configuration $(configuration) --logger 'trx' --logger 'console;verbosity=normal'
      # FIXME: The pack command below _should_ use --no-build too. Problem is
      #        that doing so when an F# project depends on a C# one causes
      #        a spurious re-build for some reason and ends up in NETSDK1085
      #   https://github.com/dotnet/fsharp/issues/12320
      dotnet pack --configuration $(configuration) --output=$(Build.ArtifactStagingDirectory)
      # Check code format. Fantomas for F#, dotnet format for C#
      dotnet tool run fantomas --check .
      dotnet format --verify-no-changes
  - task: PublishTestResults@2
    condition: always()
    inputs:
      testResultsFormat: 'VSTest'
      testResultsFiles: '**/TestResults/*.trx'
  - publish: $(Build.ArtifactStagingDirectory)
    artifact: NuGet
  - script: |
      dotnet nuget push --api-key $API_KEY --source "NuGetOrg" $(Build.ArtifactStagingDirectory)/*.nupkg
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags'))
    env:
      API_KEY: $(NuGetOrgApiKey)
