(import (scheme base)
    (scheme write))
(display (((lambda a (lambda () a)) 123)))
(display ((lambda () (define a 100) (define (b) a) a)))
(((lambda (a)
    (lambda (b) 
        (= a b)))
  (* 2 123))
 246)
;; Test non-capturing lambda inside a capturing context
(display ((lambda (x)
    (define (captures-x) x)
    (define (no-capture) 42)
    (+ (captures-x) (no-capture)))
  8))