(import (scheme base)
    (scheme write))
(display '1)(newline)
(display '"hello world")(newline)
(display '())(newline)
(display '(1 2 3))(newline)
(display (quote 1))(newline)
(display (quote "hello world"))(newline)
(display (quote ()))(newline)
(display (quote (1 2 3)))(newline)
(display (car (cdr ''''123)))(newline)
(display 'd)(newline)
(display '|\x20;|)(newline)
(display '|test\tident|)(newline)
(display '|hello world|)(newline)
(display #t)(newline)
(display ’"funky-quote-char")(newline)
