name: Build Docs

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Docket
      run: cargo install docket
    - name: Run Docket
      run: docket -s docs -t _site
    - name: Push artifact
      uses: actions/upload-pages-artifact@v0

